# Generated by Django 4.1.5 on 2023-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organaize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('adres', models.CharField(max_length=64)),
                ('responsible', models.CharField(max_length=64)),
                ('foto', models.ImageField(upload_to='')),
                ('warranty', models.FileField(upload_to='')),
                ('service', models.FileField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
